import { Product, User } from './types';

// Mock products data
export const initialProducts: Product[] = [
  {
    id: '1',
    name: 'Wireless Headphones',
    description: 'Premium noise-canceling headphones with 30-hour battery life. Experience crystal-clear audio quality with advanced noise cancellation technology.',
    price: 4800.00,
    currency: 'GHS',
    category: 'Audio',
    countInStock: 50,
    rating: 4.5,
    numReviews: 128,
    image: 'https://picsum.photos/seed/headphones/800/600',
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-15'),
  },
  {
    id: '2',
    name: 'Laptop Pro 15"',
    description: 'High-performance laptop with Intel i7 processor, 16GB RAM, and 512GB SSD. Perfect for professionals and content creators.',
    price: 20800.00,
    currency: 'GHS',
    category: 'Computers',
    countInStock: 25,
    rating: 4.8,
    numReviews: 256,
    image: 'https://picsum.photos/seed/laptop/800/600',
    createdAt: new Date('2024-01-20'),
    updatedAt: new Date('2024-01-20'),
  },
  {
    id: '3',
    name: 'Smartphone X',
    description: 'Latest flagship smartphone with 6.7" OLED display, 5G connectivity, and triple camera system. Capture stunning photos and videos.',
    price: 14400.00,
    currency: 'GHS',
    category: 'Mobile',
    countInStock: 100,
    rating: 4.6,
    numReviews: 412,
    image: 'https://picsum.photos/seed/smartphone/800/600',
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date('2024-02-01'),
  },
  {
    id: '4',
    name: 'Smart Watch Pro',
    description: 'Advanced fitness tracking smartwatch with heart rate monitor, GPS, and 7-day battery life. Stay connected and healthy.',
    price: 6400.00,
    currency: 'GHS',
    category: 'Wearables',
    countInStock: 75,
    rating: 4.4,
    numReviews: 189,
    image: 'https://picsum.photos/seed/smartwatch/800/600',
    createdAt: new Date('2024-02-10'),
    updatedAt: new Date('2024-02-10'),
  },
  {
    id: '5',
    name: 'Bluetooth Speaker',
    description: 'Portable wireless speaker with 360° sound, waterproof design, and 12-hour playtime. Perfect for outdoor adventures.',
    price: 2400.00,
    currency: 'GHS',
    category: 'Audio',
    countInStock: 120,
    rating: 4.7,
    numReviews: 324,
    image: 'https://picsum.photos/seed/speaker/800/600',
    createdAt: new Date('2024-02-15'),
    updatedAt: new Date('2024-02-15'),
  },
  {
    id: '6',
    name: 'Digital Camera 4K',
    description: 'Professional mirrorless camera with 24MP sensor, 4K video recording, and advanced autofocus. Capture life in stunning detail.',
    price: 24000.00,
    currency: 'GHS',
    category: 'Cameras',
    countInStock: 30,
    rating: 4.9,
    numReviews: 87,
    image: 'https://picsum.photos/seed/camera/800/600',
    createdAt: new Date('2024-02-20'),
    updatedAt: new Date('2024-02-20'),
  },
  {
    id: '7',
    name: 'Tablet Air 11"',
    description: 'Ultra-thin tablet with stunning display, all-day battery life, and powerful performance. Perfect for work and entertainment.',
    price: 10400.00,
    currency: 'GHS',
    category: 'Tablets',
    countInStock: 60,
    rating: 4.5,
    numReviews: 203,
    image: 'https://picsum.photos/seed/tablet/800/600',
    createdAt: new Date('2024-03-01'),
    updatedAt: new Date('2024-03-01'),
  },
  {
    id: '8',
    name: 'Gaming Console Next-Gen',
    description: 'Next-generation gaming console with 4K gaming, ray tracing, and ultra-fast SSD. Experience gaming like never before.',
    price: 8000.00,
    currency: 'GHS',
    category: 'Gaming',
    countInStock: 45,
    rating: 4.8,
    numReviews: 567,
    image: 'https://picsum.photos/seed/console/800/600',
    createdAt: new Date('2024-03-05'),
    updatedAt: new Date('2024-03-05'),
  },
];

// Initial admin user
export const initialUsers: User[] = [
  {
    id: 'admin-1',
    name: 'Admin User',
    email: 'admin@shopverse.com',
    password: 'admin123', // In production, this would be hashed
    role: 'admin',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
];
